### PR TITLE
Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by sidonath**
Hi,

As mentioned in the [previous PR](https://github.com/goodeggs/librato-node/pull/55) we wanted to update a couple of the vulnerable dependencies. So, now that tests are building, here are the actual updates!

### CODE REVIEW

**Comment by sidonath** [comment]
Yay, thanks for the quick resolution. Will there be a new release soon?

**Comment by arlophoenix** [comment]
Yes. Sorry, I started typing and then forgot to comment. I will get a release out today.

**Comment by arlophoenix** [comment]
@sidonath thanks for your contribution! It has been deployed in [v5.0.3](https://github.com/goodeggs/librato-node/releases/tag/v5.0.3).

**Comment by sidonath** [comment]
@arlophoenix Amazing! Thanks! ❤️

**Pull request merged**
