### PR TITLE
Use Librato 'counters' in addition to 'gauges'

### PR DESCRIPTION
**Pull request by mmoskal**
Currently the module reports `increment()` as Librato gauges, but librato also has a counter type (http://dev.librato.com/v1/post/metrics). This patch adds option `counters:true` to report `increment()` calls as counters.

### CODE REVIEW

**Comment by mmoskal** [comment]
After some experimenting, this is not as useful as I thought - librato expects the client to keep track of the counter, not only post increments.

**Comment by garnold** [comment]
@mmoskal That is actually the correct behavior.  Other statistics collection frameworks, such as Collectd, work the same way.  See discussion of #36 and #27.  Would love it if you'd consider reopening this pull request :+1:

**Comment by mmoskal** [comment]
Re-opened, and updated to make it work in non-distributed setting.

**Comment by garnold** [comment]
Thanks @mmoskal !

**Comment by bobzoller** [comment]
@mmoskal @garnold I think #27 / #40 (which just landed) eliminates the need for this.  It might still be nice to offer users the ability to choose gauges or counters for increment, but it seems like counters should be the default (and now they are).

I'm going to close this until we hear folks need the choice.

**Pull request closed without merging**
